### ISSUE TITLE
excuse me? May i put the downloaded data set in the original folder?

### ISSUE THREAD

**Issue by sykxiaoqiang** [sharathadavanne/seld-net#1]
when i run seld.py
then
[WinError 3] System can not find the route。: '/wrk/adavanne/DONOTREMOVE\\doa_data/label_ov1_split1_nfft512_regr0'

Process finished with exit code 1

**Comment by sykxiaoqiang** [comment]
/home/syk/anaconda2/lib/python2.7/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
Traceback (most recent call last):
  File "/home/syk/seld-net-master/seld.py", line 225, in <module>
    sys.exit(main(sys.argv))
  File "/home/syk/seld-net-master/seld.py", line 103, in main
    azi_only=params['azi_only']
  File "/home/syk/seld-net-master/cls_data_generator.py", line 41, in __init__
    self._get_label_filenames_sizes()
  File "/home/syk/seld-net-master/cls_data_generator.py", line 81, in _get_label_filenames_sizes
    for filename in os.listdir(self._label_dir):
OSError: [Errno 2] No such file or directory: '/home/syk/ov1_split1/label_ov1_split1_nfft512_regr0'

**Comment by sharathadavanne** [comment]
Hi @sykxiaoqiang thanks for using the code. You can find the answers to your question in the readme section [here](https://github.com/sharathadavanne/seld-net#training-the-seldnet-on-the-datasets). Let me know if you are still not able to get it working.

**Comment by kevinco27** [comment]
@sharathadavanne thanks for your work.
I followed the instruction in the readme section you mentioned above. But got the same issue here.

I do not change any default parameters and create the same folder structure as in cls_feature_class.py, which is "/wrk/adavanne/DONOTREMOVE/doa_data/".
 I download "ANSIM/ov1_split1.zip" to my machine  and unzip it to get "desc_ov1_split1" and "wav_ov1_split1_30db" under doa_data folder.

However, when I run seld.py script, I get OSError just like @sykxiaoqiang had. After digging into your code, I find that "self._label_dir=None" in init function of cls_feature_class.py . 
Does it means we should create "label_ov1_split1_nfft512_regr0" by ourself? but when I create the folder, I get IndexError: list index out of range. It seem that the script try to access the data in the folder I just created.

Hope you can help us to fix this issue, thanks

**Comment by sharathadavanne** [comment]
Hi @kevinco27  and @sykxiaoqiang  thanks for testing my code and finding bugs :D I have done some minor updates to the code and changed the readme to include more description.  Please check the [https://github.com/sharathadavanne/seld-net#training-the-seldnet-on-the-datasets](Training the SELDnet on the datasets) section again and see if you can get the code working. 

I think the main step that was missing in your implementation is the feature extraction part, which I had not described in the readme section earlier.

**Comment by sykxiaoqiang** [comment]
@sharathadavanne thanks,i will try the new code!

**Comment by sykxiaoqiang** [comment]
@sharathadavanne  Thank you for your work, the code is working now.
And now there is a new problem, the code about the DOA part of “Direction of arrival estimation for multiple sound sources using convolutional recurrent neural network“ does not work, then I went to ”http://tut-arg.github.io/sed_eval/” to find a whole code about DOA,but i failed to find,would i copy all of this code?
https://screenshots.firefox.com/0IxloNAmH6Np0OZA/tut-arg.github.io

**Comment by sharathadavanne** [comment]
@sykxiaoqiang This codebase is not part of the paper you are mentioning. Did you mean to say that you were trying to implement the DOA only estimation paper based on this project? Can you share more details/screenshots on what exactly is not working?

**Comment by sharathadavanne** [comment]
Hi @sykxiaoqiang the evaluation_metrics.py script contains a bunch of functions, you cannot directly call it by running `python evaluation_metrics.py`. Based on the metric you want to calculate, you will have to call the relevant function. 

The code for the DOA-only estimation paper will be released soon. Will post a link here when I upload it.

**Comment by sykxiaoqiang** [comment]
@sharathadavanne Thank you very much for your help and looking forward to your new code!
