### ISSUE TITLE
Issue with "index error" from predict_generator

### ISSUE THREAD

**Issue by nictuss** [sharathadavanne/seld-net#13]
Hi, I am trying to reproduce some experimeriments on the model, I am usng Colab and when I try to run the training process it randomly crashes with this error:
 1/37 [..............................] - ETA: 2:24Traceback (most recent call last):
  File "/content/drive/My Drive/seldnet/seld.py", line 224, in <module>
    sys.exit(e)
  File "/content/drive/My Drive/seldnet/seld.py", line 168, in main
    if params['mode'] == 'regr':
  File "/usr/local/lib/python2.7/dist-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 1522, in predict_generator
    verbose=verbose)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training_generator.py", line 435, in predict_generator
    generator_output = next(output_generator)
  File "/usr/local/lib/python2.7/dist-packages/keras/utils/data_utils.py", line 709, in get
    six.reraise(*sys.exc_info())
  File "/usr/local/lib/python2.7/dist-packages/keras/utils/data_utils.py", line 685, in get
    inputs = self.queue.get(block=True).get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 572, in get
    raise self._value
IndexError: pop from an empty deque
This error happens at the beginning of the `predict_generator` method. I can't find any fix since this not happens every time. Can you help me?
Thank you in advance.

**Comment by sharathadavanne** [comment]
Hi @nictuss I have not used colab myself, so not sure why this is happening. Did you do any code changes before running it on colab?

**Comment by nictuss** [comment]
Hi, thank you for the quick answer, I didn't change anything in the code except the local directories in cls_feature.py and set the batch_feature_extraction.py scipt to run only on ANSIM ov1. At the moment I am using colab like a linux machine so I am running the program by running the seld.py script. I really wasn't able to find any solution for this problem, because it happens randomly at the beginning of the prediction generation of the test set. Could you think at something that could generate this error?

**Comment by sharathadavanne** [comment]
The data generator code is written in such a manner, that the queue always has enough samples (self._batch_seq_len) as seen in [this line](https://github.com/sharathadavanne/seld-net/blob/3938d1d84e329e2ff90b357dfba31ee11a9da80f/cls_data_generator.py#L115). So when you actually fetch the self._batch_seq_len from both the feature and labels queue [as here](https://github.com/sharathadavanne/seld-net/blob/3938d1d84e329e2ff90b357dfba31ee11a9da80f/cls_data_generator.py#L127) you should ideally get the data without any trouble.  

At the moment I cannot imagine a scenario where this would not work! So can you debug it by keeping track of the dequeue length before filling it and before fetching from it?

**Comment by AvivShalem** [comment]
Hi @nictuss 
@orhaim and I had an academic project to get this code running and came across the same issue.
By simply addding the folowing 'if' statement to the code, the error no longer occures:

                # Read one batch size from the circular buffer
                feat = np.zeros((self._batch_seq_len, int(self._feat_len) * self._2_nb_ch))
                label = np.zeros((self._batch_seq_len, self._label_len))
                for j in range(self._batch_seq_len):

                    if len(self._circ_buf_feat) == 0:
                        break

                    feat[j, :] = self._circ_buf_feat.popleft()
                    label[j, :] = self._circ_buf_label.popleft()
                feat = np.reshape(feat, (self._batch_seq_len, int(self._feat_len), self._2_nb_ch))

Note that (as @sharathadavanne has mentioned) the '_circ_buf_feat' dequeue should always be larger than zero, so we're still not sure why and how this issue occurs, but adding the above got the code up and running.

**Comment by sharathadavanne** [comment]
Thanks for the info @avivshalem  and @orhaim. Did you also face this issue on colab?  Also, do you remember what version of python you guys were using? 

@nictuss What is your python version?

**Comment by nictuss** [comment]
Thanks for the help! @sharathadavanne  @avivshalem  @orhaim. I had this issue with both python 2.7 and python 3.6. Currently I am using python 3.6 and with this fix the problem seems to be solved.

**Comment by sharathadavanne** [comment]
Hmm, this is weird! The code looks logically right, and I can't find a case where it wouldn't work! But anyway, as long as the @avivshalem  fix works go ahead :) 

Closing this issue for now. Open it in case there are more problems :)

**Comment by avivshalem** [comment]
@sharathadavanne it indeed occured on colab, using colab's python 3.6.
