### ISSUE TITLE
How to perform MUSIC algorithm

### ISSUE THREAD

**Issue by byfaith** [sharathadavanne/seld-net#14]
I have a question about how to perform MUSIC algorithm like you did in your paper. There is only the  code of  RBMCDA particle filter . I can't get the position of each mic in the data set.  thank you.

**Comment by sharathadavanne** [comment]
Hi sorry for the really late reply. I am writing this here in case someone else comes looking for it.

For the Ambisonic format datasets. You can use the MUSIC algorithm given here in Matlab - http://research.spa.aalto.fi/projects/spharrayproc-lib/spharrayproc.html#45
The complete spatial array repo can be downloaded here - https://github.com/polarch/Spherical-Array-Processing

The circular array dataset was generated with the following configuration
circular-array microphone positions in degrees = 0, 45, 90, 135, 180, 225, 270, 315 
circular-array radius = 5 cm

For the reverberant case, the circular array was placed in the center of the room of dimension
room_dimension = 10x8x4m
receiver position = 5x4x2
