### ISSUE TITLE
DOA error

### ISSUE THREAD

**Issue by PhanLeSon03** [sharathadavanne/seld-net#16]
Great Job!
I have confused in the 'DOA error' metric:
In the paper, the 'DOA error' is the average of angle error across the frames, which means the angle error for a frame should be updated separately by 2*arcsin(delta_dis/2/R) and doing the average: DOA_err = average(2*arcsin(delta_dis/2/R)).
However, I observed in the code, the distance of the difference (delta_dis) of the frames is averaged before updating the 'DOA error': DOA_err =  2*arcsin(average(delta_dis)/2/R)

If I want to compare with your result, which one should I take. Sorry if I misunderstood!

**Comment by sharathadavanne** [comment]
You understood it correctly @PhanLeSon03 :) That was a genuine mistake from our side. The number reported in the paper uses this miscalculation.
