### ISSUE TITLE
Metrics print needs to be fixed!

### ISSUE THREAD

**Issue by JiuSenso** [sharathadavanne/seld-net#18]
There is a little thing to be fixed in _seld.py, line 218_

Actually is:
`print('SED Metrics: ER_overall: {}, F1_overall: {}'.format(sed_loss[best_epoch, 1], sed_loss[best_epoch, 0]))`

It should be like:
`print('SED Metrics: F1_overall: {}, ER_overall: {}'.format(sed_loss[best_epoch, 1], sed_loss[best_epoch, 0]))`

`ER_overall` and `F1_overall` are simply inverted, please fix it.

And thanks to the author for this repo, I use it as a starting point to implement the more recent SELD-TCN, it was really usefull.

**Comment by sharathadavanne** [comment]
Haha, @JiuSenso I agree it had been long pending! Thanks for pushing me to do it :+1: 
I have updated the code now, so closing this issue.
