### ISSUE TITLE
hello,When I train once,it only runs 350 epoch.

### ISSUE THREAD

**Issue by sykxiaoqiang** [sharathadavanne/seld-net#2]
and in once training,it loads date-set only label_ov1_split1 and spec_ov1_split1. I want to know if these date-set such as spec_ov1_split2,spec_ov1_split3,spec_ov2_split1,spec_ov2_split2,spec_ov2_split3...do not need to be loaded？
Sorry to bother you.

**Comment by sykxiaoqiang** [comment]
In addition, i want to know which script generated the two images in the folder “images”  echoic0_ov1_split1_regr3_3d0_19465735_plus5.jpg and echoic0_ov2_split1_regr3_3d0_19425208.jpg  ?
thanks u very much

**Comment by sharathadavanne** [comment]
You can change most of the parameters for training in parameter.py file. Specifically for the number of epochs, you can change it in [this line](https://github.com/sharathadavanne/seld-net/blob/9bd4bbc591ec5a42677f945b31dbe858c102b5ae/parameter.py#L31). The training uses early stopping and stops if the SELD score does not improve for 10% of your number of epochs. You can change this 10% value to your choice of percentage in [this line.]( https://github.com/sharathadavanne/seld-net/blob/9bd4bbc591ec5a42677f945b31dbe858c102b5ae/parameter.py#L39)

The current training approach, performs training for one of the chosen cross-validation split. You can choose this again in the [parameter.py file](https://github.com/sharathadavanne/seld-net/blob/9bd4bbc591ec5a42677f945b31dbe858c102b5ae/parameter.py#L17). 

The figures are being written in [this line](https://github.com/sharathadavanne/seld-net/blob/9bd4bbc591ec5a42677f945b31dbe858c102b5ae/seld.py#L60)

**Comment by sykxiaoqiang** [comment]
![2018-10-29 16-36-52](https://user-images.githubusercontent.com/39980148/47645770-e8b78800-dbac-11e8-9ac9-5f22c9df79d0.png)
I also want to ask how the middle two pictures in the screenshot are generated？

**Comment by sharathadavanne** [comment]
I dont have a generic script to do that plot. But once you train the model, you can definitely plot those by extracting the output of the trained model.
