### ISSUE TITLE
Can I use other type of audio files?

### ISSUE THREAD

**Issue by victorvargass** [sharathadavanne/seld-net#21]
Hi, can I use other type of audio files like stereo or mono (1-2 channels)?
Thanks

**Comment by sharathadavanne** [comment]
Hi @victorvargass theoretically if the directional information is present in the input feature, this network should be able to capture the location. In addition to the sound class using the spectral magnitude features.
I haven't trained this with 1-2 channels. But it will be interesting if you can do that study and report the results :)
