### ISSUE TITLE
C channel 

### ISSUE THREAD

**Issue by Joll123** [sharathadavanne/seld-net#4]
@sharathadavanne 
hi!
in the paper, speak ' The spectrogram is extracted from each of the C channels of the multichannel audio using an M-point discrete Fourier transform (DFT) on Hamming window of length M and 50% overlap.'
What is the meaning of 'C channels'. 
Thanks

**Comment by sharathadavanne** [comment]
Hi @Joll123 for this task we work with multichannel audio. Specifically, all the audio we use has four channels (first order ambisonics). So the C-channels refer to these four-channels.
