### ISSUE TITLE
what is microphone specifications

### ISSUE THREAD

**Issue by anandhupvr** [sharathadavanne/seld-net#7]
do i need any kind of microphone specification for testing this model?

**Comment by sharathadavanne** [comment]
Hi, this repo just provides the codebase to train a network that can localize and detect sound events jointly. It also provides links to datasets that you can use to train the network on. The network has been shown to learn irrespective of the microphone configuration. Obviously, the training and testing data should come from a similar microphone configuration.

**Comment by anandhupvr** [comment]
@sharathadavanne thanks
